# Generated by Django 4.2.23 on 2025-07-07 02:21

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='new_field',
            field=models.SlugField(null=True, blank=True),
        ),
    ]